POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer dummy-token

{
  "title": "Test",
  "author": "Test author",
  "url": "https://reactpatterns.com/",
  "likes": 10
}